export enum TaskType {
  SERVER_HOST_MAINTENANCE    = 'SERVER_HOST_MAINTENANCE',
  WINDOWS_DOMAIN_MAINTENANCE = 'WINDOWS_DOMAIN_MAINTENANCE',
  QNAP_MAINTENANCE           = 'QNAP_MAINTENANCE',
  VEEAM_BACKUP               = 'VEEAM_BACKUP',
  ROUTER_MAINTENANCE         = 'ROUTER_MAINTENANCE',
  TERMINAL_MAINTENANCE       = 'TERMINAL_MAINTENANCE',
  SITE_VISIT                 = 'SITE_VISIT',
  AV_CONTROL                 = 'AV_CONTROL',
  UPS_CONTROL                = 'UPS_CONTROL',
  ENDPOINT_INVENTORY         = 'ENDPOINT_INVENTORY',
}
