export enum TaskType {
  SERVER_MAINTENANCE = 'SERVER_MAINTENANCE',
  TERMINAL_MAINTENANCE = 'TERMINAL_MAINTENANCE',
  SITE_VISIT = 'SITE_VISIT',
  AV_CONTROL = 'AV_CONTROL',
  UPS_CONTROL = 'UPS_CONTROL',
  ENDPOINT_INVENTORY = 'ENDPOINT_INVENTORY',
}
